service: apollo-lambda
provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
functions:
  graphql:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: graphql.handler
    events:
    - http:
        path: graphql
        method: post
        cors: true
        authorizer:
          name: authorizer
          arn: arn:aws:cognito-idp:eu-west-1:673184037824:userpool/eu-west-1_K2m1icWIj

    - http:
        path: graphql
        method: get
        cors: true
